### ISSUE TITLE
Criterion/Main/Options.hs:38:48: error:     Module ‘Options.Applicative.Help.Pretty’ does not export ‘Ann’    | 38 | import Options.Applicative.Help.Pretty ((.$.), Ann)

### ISSUE THREAD

**Issue by rmourey26** [haskell/criterion#243]
Ubuntu 20.04 focal fossa, 86x_64-linux, ghc 8.10.5, cabal 3.4.0.0 -----

failing cabal build criterion, also failing integration in a large project for same error

Criterion/Main/Options.hs:38:48: error:
    Module ‘Options.Applicative.Help.Pretty’ does not export ‘Ann’
   |
38 | import Options.Applicative.Help.Pretty ((.$.), Ann)

builds 7 of 12 library components and fails on the 8th

**Comment by RyanGlScott** [comment]
What versions of `criterion` and `optparse-applicative` (a dependency of `criterion`) are you building?

**Comment by rmourey26** [comment]
My apologies,...1.5.9.0 criterion and optparse-applicative >=0.13 pointing to latest repo 0.16.1.0

**Comment by rmourey26** [comment]
--I removed ",Ann" from line 38
--added import Text.PrettyPrint.ANSI.Leijen (pretty, Doc, text) 
--added ansi-wl-pprint >= 0.6.9 cabal file dependency

and it completed the build process and installed using 8.10.4 ghc

**Comment by RyanGlScott** [comment]
Thanks. I'm a bit confused by this bug report, as I'm unable to reproduce the issue using the versions of `criterion`/`optparse-applicative` that you mentioned. What's more, this is line 38 of `Criterion/Main/Options.hs` in `criterion-1.5.9.0`:

https://github.com/haskell/criterion/blob/019a1b93391e20fd3cb335b9136c6a4a6ce398e4/Criterion/Main/Options.hs#L38

This doesn't import `Ann`, which differs from what the error message in https://github.com/haskell/criterion/issues/243#issue-967952246 shows. Are you sure you are using the original, unmodified version of `criterion-1.5.9.0` from Hackage?

**Comment by rmourey26** [comment]
> Thanks. I'm a bit confused by this bug report, as I'm unable to reproduce the issue using the versions of `criterion`/`optparse-applicative` that you mentioned. What's more, this is line 38 of `Criterion/Main/Options.hs` in `criterion-1.5.9.0`:
> 
> https://github.com/haskell/criterion/blob/019a1b93391e20fd3cb335b9136c6a4a6ce398e4/Criterion/Main/Options.hs#L38
> 
> This doesn't import `Ann`, which differs from what the error message in [#243 (comment)](https://github.com/haskell/criterion/issues/243#issue-967952246) shows. Are you sure you are using the original, unmodified version of `criterion-1.5.9.0` from Hackage?

Thanks for your time and your assistance! The repo at https://github.com/input-output-hk/criterion.git  indicates that its a fork of the Haskell/criterion repo, albeit a fork that is one commit ahead of the Haskell master. Somehow throughout this process and before I submitted this issue, I thought I saw that both IOHK and Haskells master had 'Ann' added to line 38 but I was mistaken! I apologize for the confusion on this!
