### ISSUE TITLE
Regressions in Config Parameter are Ignored

### ISSUE THREAD

**Issue by julianbrunner** [haskell/criterion#244]
I want to configure GC allocation regression. For this, I create the configuration `defaultConfig { regressions = [(["iters"], "allocated")] }` and pass it to `defaultMainWith`. However, it seems to have no effect.

Skimming through the sources briefly, it seems that `Criterion.Main.Options.config` is not reading the `regressions` field of the passed `Config`, only honoring the command-line parameters. However, I am not familiar with the parsing code, so maybe I am reading things wrong.

**Comment by RyanGlScott** [comment]
Thanks for the bug report! I agree that `defaultMainWith` should pass through the default value of `regressions`, and the fact that this doesn't happen is an oversight.

I've submitted #245, which I believe should fix the issue. Can you verify that it works for your needs?

**Comment by RyanGlScott** [comment]
I'm pretty sure that I fixed this in #245, so I went ahead and uploaded [`criterion-1.5.10.0`](https://hackage.haskell.org/package/criterion-1.5.10.0) to Hackage with these changes. Thanks again!
