### ISSUE TITLE
Examples directory link is wrong on Hackage Readme

### ISSUE THREAD

**Issue by turion** [haskell/criterion#279]
While the readme file links correctly to the examples directory when one clicks on it from github, it does not link correctly when one clicks on it from hackage: https://hackage.haskell.org/package/criterion There, it links to https://hackage.haskell.org/examples, which doesn't exist.

**Comment by RyanGlScott** [comment]
Well spotted. For whatever reason, the `README` was using HTML to link to a subdirectory of the `criterion` repo, and I imagine that this only works properly when clicking the links from GitHub itself. I've switched to a more portable approach to hyperlinking in #280.
